/**
 * Regenerate core/cascade/generated.ts from the Foundry build and the Sepolia deployment book.
 *
 *   forge build && npm run gen
 *
 * Run after any contract change or `setup --redeploy`, so the terminal demo and the web UI read the
 * same ABIs and addresses. The output is committed: the web app builds without Foundry.
 */
import { readFileSync, writeFileSync } from "node:fs";

const abi = (name: string, dir = `${name}.sol`) => JSON.parse(readFileSync(`out/${dir}/${name}.json`, "utf8")).abi;
const book = JSON.parse(readFileSync("deployments/sepolia.json", "utf8"));

const out = `// GENERATED by scripts/gen-core.ts from out/ and deployments/sepolia.json — do not edit by hand.
// Regenerate: forge build && npm run gen

/** Current Sepolia deployment (ENSv2 beta). Retired addresses stay in deployments/sepolia.json. */
export const SEPOLIA = ${JSON.stringify({ parent: book.parent, cascade: book.cascade, team: book.team, attacker: book.attacker }, null, 2)} as const;

export const CASCADE_ABI = ${JSON.stringify(abi("CascadeSubregistry"))} as const;

export const TEAM_ABI = ${JSON.stringify(abi("TeamRegistry"))} as const;
`;
writeFileSync("core/cascade/generated.ts", out);
console.log(`wrote core/cascade/generated.ts (cascade ${book.cascade}, team ${book.team})`);
