/**
 * Regenerate core/cascade/generated.ts from the Foundry build and the Sepolia deployment book.
 *
 *   forge build && npm run gen
 *
 * Run after any contract change or `setup --redeploy`, so the terminal demo and the web UI read the
 * same ABIs and addresses. The output is committed: the web app builds without Foundry.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";

const abi = (name: string, dir = `${name}.sol`) => JSON.parse(readFileSync(`out/${dir}/${name}.json`, "utf8")).abi;
const book = JSON.parse(readFileSync("deployments/sepolia.json", "utf8"));

const out = `// GENERATED by scripts/gen-core.ts from out/ and deployments/sepolia.json — do not edit by hand.
// Regenerate: forge build && npm run gen

/** Current Sepolia deployment (ENSv2 beta). Retired addresses stay in deployments/sepolia.json. */
export const SEPOLIA = ${JSON.stringify({ parent: book.parent, cascade: book.cascade, team: book.team, attacker: book.attacker }, null, 2)} as const;

export const CASCADE_ABI = ${JSON.stringify(abi("CascadeSubregistry"))} as const;

export const TEAM_ABI = ${JSON.stringify(abi("TeamRegistry"))} as const;
`;
writeFileSync("core/cascade/generated.ts", out);
console.log(`wrote core/cascade/generated.ts (cascade ${book.cascade}, team ${book.team})`);

// Roadmap branch: CascadeSubregistryV2 on its own tree (acme-labs.eth), from deployments/sepolia-v2.json.
// The tree the web app shows: CASCADE_TREE=acme|orbit (default orbit), from its own deployment book.
const V2_BOOK = (process.env.CASCADE_TREE ?? "orbit") === "acme" ? "deployments/sepolia-v2.json" : "deployments/sepolia-orbit.json";
if (existsSync(V2_BOOK)) {
  const v2 = JSON.parse(readFileSync(V2_BOOK, "utf8"));
  const outV2 = `// GENERATED by scripts/gen-core.ts from out/ and ${V2_BOOK} — do not edit by hand.
// Regenerate: forge build && npm run gen

/** The cascade demo's deployment (CascadeSubregistryV2), from ${V2_BOOK}. Separate from the v1 demo's contracts. */
export const SEPOLIA_V2 = ${JSON.stringify({ org: v2.org, cascade: v2.cascade, devTeam: v2.devTeam, sre: v2.sre, security: v2.security }, null, 2)} as const;

export const CASCADE_V2_ABI = ${JSON.stringify(abi("CascadeSubregistryV2"))} as const;

export const NESTED_TEAM_ABI = ${JSON.stringify(abi("NestedTeam"))} as const;
`;
  writeFileSync("core/cascade/generated-v2.ts", outV2);
  console.log(`wrote core/cascade/generated-v2.ts (v2 cascade ${v2.cascade})`);
}
